### ISSUE TITLE
Windows gives an Error because of an assertion.

### ISSUE THREAD

**Issue by bernardosulzbach** [mafagafogigante/lyric-guesser#19]
```
Traceback (most recent call last):
  File "C:\Users\Bernardo\Desktop\lyrics-master\main.py", line 187, in <module>
    mainloop()
  File "C:\Users\Bernardo\Desktop\lyrics-master\main.py", line 140, in mainloop
    random_song = guesser.songs.Song(**guesser.loader.get_random_song())
  File "C:\Users\Bernardo\Desktop\lyrics-master\guesser\songs.py", line 7, in __init__
    assert isinstance(artist, str), "artist should be a string"
AssertionError: artist should be a string
```

**Comment by bernardosulzbach** [comment]
This was because I was using Python 2. Use Python 3.
